"""Rename timestamp to created_at in like table

Revision ID: 66c2f93e66d5
Revises: 0383d57c757e
Create Date: 2025-05-21 08:33:57.609461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c2f93e66d5'
down_revision = '0383d57c757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
