"""Rename timestamp to created_at in like table

Revision ID: 79233a85a65a
Revises: 39af40abba12
Create Date: 2025-05-21 14:38:13.597067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79233a85a65a'
down_revision = '39af40abba12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
